services:
  openedai-vision:
    build:
      args:
        - VERSION=latest
      dockerfile: Dockerfile
    container_name: openedai-vision
    image: ghcr.io/matatonic/openedai-vision
    env_file: vision.env # your settings go here
    volumes:
      - ./hf_home:/app/hf_home  # for Hugginface model cache
      - ./model_conf_tests.json:/app/model_conf_tests.json
    ports:
      - 5006:5006
    #runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #device_ids: ['0', '1'] # Select a gpu, or
              count: all
              capabilities: [gpu]
