services:
  server:
    build:
      dockerfile: Dockerfile.yi-vl
    tty: true
    image: ghcr.io/matatonic/yi-vl
    environment:
      - HF_HOME=/app/hf_home
    volumes:
      - ./hf_home:/app/hf_home
    ports:
      - 5006:8000
    command: python VL/openai_api.py --model-path 01-ai/Yi-VL-34B
    #command: python VL/openai_api.py --model-path 01-ai/Yi-VL-6B
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #device_ids: ['0', '1'] # Select a gpu, or
              count: all
              capabilities: [gpu]
