services:
  openedai-vision-alt:
    build:
      args:
        - VERSION=alt
        - USER_ID=${UID:-1000}
        - GROUP_ID=${GID:-1000}
      dockerfile: Dockerfile
    user: ${UID:-1000}:${GID:-1000}
    container_name: openedai-vision-alt
    image: ghcr.io/matatonic/openedai-vision-alt
    env_file: vision-alt.env # your settings go here
    volumes:
      - ./hf_home:/app/hf_home  # for Hugginface model cache
      - ./model_conf_tests.alt.json:/app/model_conf_tests.json
    ports:
      - 5006:5006
    #runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #device_ids: ['0', '1'] # Select a gpu, or
              count: all
              capabilities: [gpu]
